### ISSUE TITLE
Repo Organization

### ISSUE THREAD

**Issue by ericwilliamsneu** [rr2039/RR-2019-Deep-Space#3]
Can someone provide me with an overview of how we've organized the repository? It appears we've got different features in sub-folders in the same repository. If that's the case, we should consider reorganizing this as a mainline and feature branch system. Let me know if you want help with that.

**Comment by graykevinb** [comment]
So instead of creating branches we create folders. Each member of the team has their own code folders which no one touches. Instead if one wants to modify the code they copy it and modify it. I am complete favor of using git properly and would be more than happy to help switch.
